---
# Common role tasks

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true


- name: Install basic packages
  ansible.builtin.apt:
    name:
      - curl
      - git
      - vim
    state: present
  become: true