variable "pm_api_url" {}
variable "pm_user" {}
variable "pm_password" {}
variable "pm_node" {}
variable "web_vmid" {}
variable "template_name" {}
variable "network_bridge" {}
variable "web_ip" {}
variable "gateway" {}
variable "ssh_public_key" {}
variable "web_password" {}